"""Create a new Program page structure in Confluence.

Creates the following hierarchy under the PMO Project Portfolio space:

    Product Development Projects
    └── <Program Name> Program          (created if missing)
        ├── CEO Review                  (created if missing)
        └── Projects/Releases           (created if missing)

The spin-up wizard expects this layout — without a "Projects/Releases" child
page under the program page, Charters get placed directly under the program
page as a silent fallback.

Usage:
    python scripts/create_program_pages.py "HOP Reporting System"

The script is idempotent: if a page already exists with the expected title,
it is skipped and its ID is reported.
"""
from __future__ import annotations

import asyncio
import logging
import sys
from pathlib import Path

# Allow running as ``python scripts/create_program_pages.py`` from the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.config import settings  # noqa: E402
from src.connectors.base import ConnectorError  # noqa: E402
from src.connectors.confluence import ConfluenceConnector  # noqa: E402

logger = logging.getLogger(__name__)

# Parent page under which all programs sit. This is a stable Confluence
# concept (see docs/confluence-structure.md).
PARENT_PAGE_TITLE = "Product Development Projects"

# Minimal page body (storage format). The program page itself is a container;
# it does not need a rich template.
_EMPTY_BODY = (
    '<p>Auto-generated by Project Seat. Edit this page to add program-level '
    "context, links, and owners.</p>"
)


async def _find_page_id(conf: ConfluenceConnector, space_key: str, title: str) -> str | None:
    """Return the page ID for an exact-title match in the given space."""
    results = await conf.search_pages(space_key, title)
    if not results:
        return None
    return str(results[0]["id"])


async def _find_child_by_title(conf: ConfluenceConnector, parent_id: str, title: str) -> str | None:
    children = await conf.get_page_children(parent_id)
    for child in children:
        if child.get("title", "").strip() == title:
            return str(child["id"])
    return None


async def _ensure_child(
    conf: ConfluenceConnector,
    space_key: str,
    parent_id: str,
    title: str,
    body: str = _EMPTY_BODY,
) -> tuple[str, bool]:
    """Create ``title`` under ``parent_id`` if missing. Returns (page_id, created)."""
    existing = await _find_child_by_title(conf, parent_id, title)
    if existing:
        return existing, False
    page = await conf.create_page(space_key, title, body, parent_id=parent_id)
    return str(page["id"]), True


async def main(program_name: str) -> int:
    space_key = settings.atlassian.confluence_space_key
    conf = ConfluenceConnector()
    try:
        root_id = await _find_page_id(conf, space_key, PARENT_PAGE_TITLE)
        if not root_id:
            print(
                f"ERROR: Could not find parent page '{PARENT_PAGE_TITLE}' in space "
                f"'{space_key}'. Check CONFLUENCE_SPACE_KEY in .env.",
                file=sys.stderr,
            )
            return 1
        print(f"Found '{PARENT_PAGE_TITLE}' (id={root_id}) in space {space_key}")

        program_title = f"{program_name} Program"
        program_id, created = await _ensure_child(conf, space_key, root_id, program_title)
        print(f"  {'CREATED' if created else 'exists '} {program_title} (id={program_id})")

        # Confluence Cloud requires page titles to be unique within a space, so child
        # pages are prefixed with the program name. Spin-up / CEO-review discovery uses
        # substring matching ("Projects"+"Releases" / "CEO Review") so prefixed titles
        # still resolve correctly.
        releases_title = f"{program_name} Projects/Releases"
        releases_id, created = await _ensure_child(conf, space_key, program_id, releases_title)
        print(f"  {'CREATED' if created else 'exists '} {releases_title} (id={releases_id})")

        ceo_title = f"{program_name} CEO Review"
        ceo_id, created = await _ensure_child(conf, space_key, program_id, ceo_title)
        print(f"  {'CREATED' if created else 'exists '} {ceo_title} (id={ceo_id})")

        print("\nDone. You can now spin up projects under this program.")
        return 0
    except ConnectorError as exc:
        print(f"ERROR: Confluence API call failed: {exc}", file=sys.stderr)
        return 2
    finally:
        await conf.close()


if __name__ == "__main__":
    logging.basicConfig(level=logging.WARNING)
    if len(sys.argv) != 2:
        print("Usage: python scripts/create_program_pages.py \"<Program Name>\"", file=sys.stderr)
        print("Example: python scripts/create_program_pages.py \"HOP Reporting System\"", file=sys.stderr)
        sys.exit(2)
    sys.exit(asyncio.run(main(sys.argv[1])))
